config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('/admin/hotel')


  # devise_for :users, :sign_out_via => [ :get ]

  namespace :admin do
    resources :hotel do
      get 'export', on: :collection
    end

    resources :reserva do
      get 'export', on: :collection
    end
    resources :hospede do
      get 'export', on: :collection
    end
    resources :quarto do
      get 'export', on: :collection
    end
    
  end
  

end

app/models/reserva.rb
class Reserva < ApplicationRecord
    belongs_to :cliente
    belongs_to :quarto 

    scope :filter_by_cliente, -> (cliente_id) { where cliente_id: cliente_id }
end

app/controllers/admin/reserva_controller.rb
require_relative '../../reports/generate_pdf'
require_relative '../../reports/generate_csv'
class Admin::ReservaController < ApplicationController
    layout "admin"

    def index
        @modulo = "Lista de Reservas"
        @reservas = Reserva.all.page params[:page]
        @reservas  = @reservas.filter_by_cliente(params[:cliente_id]) if params[:cliente_id].present?
    end

    def new
        @modulo = "Adicionar Reservas"
        @reserva = Reserva.new
    end

    def create
        @reserva = Reserva.new(reserva_params)
        if @reserva.save
          @quarto = Quarto.find(reserva_params[:quarto_id])
          @quarto.reservado = true
          @quarto.save
          redirect_to admin_reserva_index_path
        else
          render :new
        end
    end 

    def edit
        @modulo = "Editar Reservas"
        @reserva = Reserva.find(params[:id])
    end
  
    def update
      @reserva = Reserva.find(params[:id])
  
      if @reserva.update(reserva_params)
        redirect_to admin_reserva_index_path
      else
        render :edit
      end
    end

    def export
      @reservas = Reserva.all
      @reservas  = @reservas.filter_by_cliente(params[:cliente_id]) if params[:cliente_id].present?
      
      respond_to do |format|
        format.pdf do
          send_pdf
        end
        format.csv do
          send_csv
        end
      end
    end
    
    private
      def reserva_params
        params.require(:reserva).permit(:quarto_id, :data_reserva, :check_in, :check_out, :preco_total, :cliente_id)
      end
    
      def send_pdf
        itens = []
        for reserva in @reservas do
          item = {
            cliente:reserva.cliente.nome,
            check_in:reserva.check_in.strftime(" %d/%m/%Y"),
            check_out:reserva.check_out.strftime(" %d/%m/%Y"),
            preco_total:reserva.preco_total
          }
          itens.push(item)
        end
        colsname = {cliente: 'Cliente', check_in: 'Check in', check_out:'Check out', preco_total:'Preço total'}
        widths = [135, 135, 135, 135]

        relatorio = GeneratePdf.new("Lista de Reservas", itens, colsname, widths)
        pdf = relatorio.pdf
        send_data(pdf, filename: 'relatorio.pdf', type: 'application/pdf', disposition: :inline)
      end

      def send_csv
        colsname = {cliente_id: 'Hotel', check_in: 'Check in', check_out:'Check out'}
  
        relatorio = GenerateCsv.new( @reservas, colsname)
        csv = relatorio.csv
        send_data(csv, filename:'relatorio.csv', type:'text/csv')
      end
end

app/helpers/admin/reserva_helper.rb
module Admin::ReservaHelper
    def show_hotel_quarto(reserva)
        quarto = reserva.quarto
        "#{quarto.hotel.nome}/ Quarto #{quarto.numero}"
    end
end

app/views/admin/reserva/_form.html.erb
<%= form_with model: reserva, url:url	 do |f|%>
  <div class="mb-3">
    <%= f.label :quarto, "Quarto", class:"form-label" %>
    <%= f.collection_select(:quarto_id, Quarto.quarto_livre, :id, :numero, {} , {class: "form-select"})%>
  </div>

  <div class="mb-3">
    <%= f.label :data_reserva, "Data da Reserva", class:"form-label" %>
    <%= f.date_field :data_reserva, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :check_in, "Check In", class:"form-label" %>
    <%= f.date_field :check_in, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :check_out, "Check Out", class:"form-label" %>
    <%= f.date_field :check_out, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :preco_total, "Preço", class:"form-label" %>
    <%= f.number_field :preco_total, step: 0.1, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :cliente, "Cliente", class:"form-label" %>
    <%= f.collection_select(:cliente_id, Cliente.all, :id, :nome, {}, {class:"form-select"}) %>
  </div>


  <%= f.submit "Salvar", class:"btn btn-primary" %>
<% end %>

app/views/admin/reserva/edit.html.erb
<% content_for :main do %>
  <div class="p-5">
    <%= render partial: "form", locals: {reserva: @reserva, url:admin_reserva_path(@reserva)}  %>
  </div>
<% end %>

app/views/admin/reserva/index.html.erb
<% content_for :title do %> Lista de reservas<% end %>

<% content_for :main do %>

  <div class="py-3">
    <span>Filtros</span>
    <%= form_with url: admin_reserva_index_path, method: :get do |form| %>
      <div class="px-3 py-2 border d-flex">
        <div class="mb-3 me-2">
          <%= form.label :hotel, "Clientes:", class: "form-label"%>
          <%= form.collection_select(:cliente_id, Cliente.all, :id, :nome, {:prompt => "Todos", :selected => params[:hotel_id]}, {class:"form-select"}) %>
        </div>
        <%= form.submit "Search", class: "mt-3 btn btn-primary align-self-center"%>
      </div>
    <% end %>
  </div>

  <div class="py-3 d-flex">
    <%= render "shared/button_create", locals: {nome: "Nova Reserva", url: new_admin_reserva_path} %>
    <div class="ms-3">
      <%= render partial: "shared/button_export", locals: {url: -> (f){export_admin_reserva_index_path(format:f)}}%>
    </div>
  </div>
  <div>
    <table class="table">
      <thead>
        <tr>
          <th scope="col" width="50px">#</th>
          <th scope="col">Hóspede</th>
          <th scope="col">Hotel/Quarto</th>
          <th scope="col">Check-in</th>
          <th scope="col">Check-out</th>
          <th scope="col" width="15%"></th>
        </tr>
      </thead>
      <tbody>
        <% @reservas.each_with_index do |item, i| %>
          <tr>
            <th scope="row"><%= "#{i}" %></th>
            <td><%= item.cliente.nome%></td>
            <td><%= show_hotel_quarto(item) %></td>
            <td><%= datatime_br(item.check_in) %></td>
            <td><%= datatime_br(item.check_out) %></td>
            <td>
              <button type="button"  class="btn btn-delete" data-url='<%=admin_quarto_path(item)%>' >
                <i class="bi bi-trash"></i>
              </button>
              <%= link_to(edit_admin_reserva_path(item), class: 'btn') do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div>
    <%= paginate @reservas, window: 2 %>
  </div>
  <%= render "shared/modal_delete" %>
<% end %>

app/views/admin/reserva/new.html.erb
<% content_for :main do %>
  <div class="p-5">
    <%= render partial: "form", locals: {reserva: @reserva, url:admin_reserva_index_path}  %>
  </div>
<% end %>