config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('/admin/hotel')


  # devise_for :users, :sign_out_via => [ :get ]

  namespace :admin do
    resources :hotel do
      get 'export', on: :collection
    end

    resources :reserva do
      get 'export', on: :collection
    end
    resources :hospede do
      get 'export', on: :collection
    end
    resources :quarto do
      get 'export', on: :collection
    end
    
  end
  

end

app/models/quarto.rb
class Quarto < ApplicationRecord
    belongs_to :hotel
    belongs_to :quarto_tipo
    has_many :reservas, :dependent => :delete_all 
    has_many :clientes, through: :reservas, :dependent => :delete_all 

    scope :quarto_livre, -> { where(reservado: false) }
    scope :filter_by_hotel, -> (hotel_id) { where hotel_id: hotel_id }
end

app/controllers/admin/quarto_controller.rb
require_relative '../../reports/generate_pdf'
require_relative '../../reports/generate_csv'

class Admin::QuartoController < ApplicationController
  layout "admin"

  def index 
    @modulo = "Lista de Quartos"
    @quartos = Quarto.all.page params[:page]
    @quartos  = @quartos.filter_by_hotel(params[:hotel_id]) if params[:hotel_id].present?
  end

  def new
    @modulo = "Adicionar Quarto"
    @quarto = Quarto.new
  end

  def create
    @quarto = Quarto.new(quarto_params)
    if @quarto.save
      redirect_to admin_quarto_index_path
    else
      render :new
    end
  end

  def edit
    @modulo = "Editar Quarto"
    @quarto = Quarto.find(params[:id])
  end
  def destroy
    Quarto.find_by(id: params[:id]).destroy
    redirect_to admin_quarto_index_path
end

  def update
    @quarto = Quarto.find(params[:id])

    if @quarto.update(quarto_params)
      redirect_to admin_quarto_index_path
    else
      render :edit
    end
  end

  def export
    @quartos = Quarto.all
    @quartos  = @quartos.filter_by_hotel(params[:hotel_id]) if params[:hotel_id].present?

    respond_to do |format|
      format.pdf do
        send_pdf
      end
      format.csv do
        send_csv
      end
    end
  end

  private
    def quarto_params
      params.require(:quarto).permit(:hotel_id, :quarto_tipo_id, :numero, :descricao, :capacidade, :preco, :reservado)
    end
    def send_pdf
      itens = []
      for quarto in @quartos do
        puts quarto.inspect
        item = {
          hotel:quarto.hotel.nome,
          quarto_tipo:quarto.quarto_tipo.nome,
          numero:quarto.numero,
          capacidade:quarto.capacidade,
          preco:quarto.preco
        }
        
        itens.push(item)
      end
      colsname = {hotel: 'Hotel', quarto_tipo: 'Quarto Tipo', numero:'Numero', capacidade:'Capacidade', preco:'Preço'}
      widths = [90,90,90,90,90,90]

      relatorio = GeneratePdf.new("Lista de Hoteis", itens, colsname, widths)
      pdf = relatorio.pdf
      send_data(pdf, filename: 'relatorio.pdf', type: 'application/pdf', disposition: :inline)
  end

    def send_csv
      colsname = {hotel_id: 'Hotel', quarto_tipo_id: 'Quarto tipo', preco:'Preco'}

      relatorio = GenerateCsv.new( @quartos, colsname)
      csv = relatorio.csv
      send_data(csv, filename:'relatorio.csv', type:'text/csv')
    end

end

app/helpers/admin/quarto_helper.rb
module Admin::QuartoHelper
  
end

app/views/admin/quarto/_form.html.erb
<%= form_with model: quarto, url:url	 do |f|%>
    <div class="mb-3">
      <%= f.label :hotel, "Hotel", class:"form-label" %>
      <%= f.collection_select(:hotel_id, Hotel.all, :id, :nome, {}, {class:"form-select"}) %>
    </div>
    <div class="mb-3">
      <%= f.label :quarto_tipo, "Quarto tipo", class:"form-label" %>
      <%= f.collection_select(:quarto_tipo_id, QuartoTipo.all, :id, :nome, {}, {class:"form-select"})%>
    </div>
    <div class="mb-3">
      <%= f.label :numero, "Numero", class:"form-label" %>
      <%= f.number_field :numero, class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :descricao, "Descrição", class:"form-label" %>
      <%= f.text_field :descricao, class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :capacidade, "Capacidade", class:"form-label" %>
      <%= f.number_field :capacidade, class:"form-control" %>
    </div>
    <div class="mb-3">
      <%= f.label :preco, "Preço", class:"form-label" %>
      <%= f.number_field :preco, step: 0.1, class:"form-control" %>
    </div>
      <%= f.label "Reservado", class:"form-label" %>
      <%= f.check_box :reservado, class:"form-check" %>
    </div>
    <%= f.submit "Salvar", class:"btn btn-primary" %>
  <% end %>

app/views/admin/quarto/edit.html.erb
<% content_for :main do %>
  <div class="p-5">
    <%= render partial: "form", locals: {quarto: @quarto, url:admin_quarto_path(@quarto)}  %>
  </div>
<% end %>

app/views/admin/quarto/index.html.erb
<% content_for :main do %>
  
  <div class="py-3">
    <span>Filtros</span>
    <%= form_with url: admin_quarto_index_path, method: :get do |form| %>
      <div class="px-3 py-2 border d-flex">
        <div class="mb-3 me-2">
          <%= form.label :hotel, "Hotel:", class: "form-label"%>
          <%= form.collection_select(:hotel_id, Hotel.all, :id, :nome, {}, {class:"form-select"}) %>
        </div>
        <%= form.submit "Search", class: "mt-3 btn btn-primary align-self-center"%>
      </div>
    <% end %>
  </div>

  <div class="py-3 d-flex">
    <%= render "shared/button_create", locals: {nome: "Novo Quarto", url:new_admin_quarto_path() } %>
    <div class="ms-3">
      <%= render partial: "shared/button_export", locals: {url: -> (f){export_admin_quarto_index_path(format:f)}} %>
    </div>
  </div>
  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Hotel</th>
      <th scope="col">Numero</th>
      <th scope="col">Descrição</th>
      <th scope="col">Preço</th>
      <th scope="col" width="15%"></th>
    </tr>
  </thead>
  <tbody>
    <% @quartos.each_with_index do |item, i| %>
      <tr>
        <th scope="row"><%= "#{i}" %></th>
        <td><%= item.hotel.nome%></td>
        <td><%= item.numero %></td>
        <td><%= item.descricao %></td>
        <td><%= item.preco %></td>
        <td>
          <button type="button"  class="btn btn-delete" data-url='<%=admin_quarto_path(item)%>' >
            <i class="bi bi-trash"></i>
          </button>
          <%= link_to(edit_admin_quarto_path(item), class: 'btn') do %>
            <i class="bi bi-pencil-square"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

<div>
  <%= paginate @quartos, window: 2 %>
</div>

<%= render "shared/modal_delete" %>

<% end %>

app/views/admin/quarto/new.html.erb
<% content_for :main do %>
    <div class="p-5">
      <%= render partial: "form", locals: {quarto: @quarto, url:admin_quarto_index_path}  %>
    </div>
<% end %>