config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('/admin/hotel')


  # devise_for :users, :sign_out_via => [ :get ]

  namespace :admin do
    resources :hotel do
      get 'export', on: :collection
    end

    resources :reserva do
      get 'export', on: :collection
    end
    resources :hospede do
      get 'export', on: :collection
    end
    resources :quarto do
      get 'export', on: :collection
    end
    
  end
  

end

app/views/shared/_bar_admin.html.erb
<div class="position-relative">
  <%= image_tag("morcego.png", alt: "morcego", class: "position-absolute morcego-icon") %>
  <div class="py-1 px-3 position-relative module-bar">
    <h4 class="pt-1 fs-5"> <%= (@modulo.present?) ? @modulo.upcase : "MÓDULO"%> </h4>
  </div>
<div>

app/views/shared/_button_create.html.erb
<a class="btn btn-primary btn-create" href="<%=locals[:url]%>" role="button">
   <i class="bi bi-plus-circle"></i> 
    <%= locals[:nome] %>
</a>

app/views/shared/_button_export.html.erb
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle btn-export" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Exportar
  </button> 
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" href="<%= url.call('pdf') %>">PDF</a></li>
    <li><a class="dropdown-item" href="<%= url.call('csv') %>">CSV</a></li>
  </ul>
</div>

app/views/shared/_menu_admin.html.erb
<ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link <%= active_link(admin_reserva_index_path)%>" aria-current="page" href="/admin/reserva">
      <i class="bi bi-credit-card-2-front-fill me-1"></i>
      Reservas
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= active_link(admin_hotel_index_path)%>" href="/admin/hotel">
      <i class="bi bi-house-door-fill me-1"></i>
      Hoteis
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= active_link(admin_quarto_index_path)%>" href="/admin/quarto">
    <i class="bi bi-lamp-fill"></i>
      Quarto
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= active_link(admin_hospede_index_path)%>" href="/admin/hospede">
      <i class="bi bi-person-lines-fill me-1"></i>
      Hóspedes
    </a>
  </li>
</ul>

<h6 class="sidebar-heading px-3 mt-4 mb-1 text-muted">
  <span>Usuário</span>
</h6>
<ul class="nav flex-column mb-2">
  <li class="nav-item">
    <%= link_to(destroy_user_session_path(), method: :delete, class: "nav-link text-danger bg-transparent") do%>
      <i class="bi bi-door-closed-fill me-1"></i>
      Logout 
    <%end%>
  </li>
</ul>

app/views/shared/_modal_delete.html.erb
<!-- Modal -->
<div class="modal fade" id="modalDelete" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Deseja deletar?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
       Deseja deletar esse item?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Não</button>
        <%=link_to "Sim", "", method: :delete, class: "btn btn-primary modal-btn-delete"%>
      </div>
    </div>
  </div>
</div>