config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect('/admin/hotel')


  # devise_for :users, :sign_out_via => [ :get ]

  namespace :admin do
    resources :hotel do
      get 'export', on: :collection
    end

    resources :reserva do
      get 'export', on: :collection
    end
    resources :hospede do
      get 'export', on: :collection
    end
    resources :quarto do
      get 'export', on: :collection
    end
    
  end
  

end

app/controllers/admin/hospede_controller.rb
require_relative '../../reports/generate_pdf'
require_relative '../../reports/generate_csv'

class Admin::HospedeController < ApplicationController
    layout "admin"
    
    def index
        @modulo = "Lista de Hospedes"
        @hospede = Cliente.all.page params[:page]
        @hospede  = @hospede.filter_by_starts_with(params[:nome]) if params[:nome].present?
    end

    def show
        @hospede = Cliente.find(params[:id])
    end
      
    def destroy
        Cliente.find_by(id: params[:id]).destroy
        redirect_to admin_hospede_index_path
    end

    def new
        @modulo = "Adicionar Hospedes"
        @hospede = Cliente.new
    end

    def create
        @hospede = Cliente.new(hospede_params)
        if @hospede.save
          redirect_to admin_hospede_index_path
        else
          render :new
        end
    end 

    def edit
        @modulo = "Editar Hospedes"
        @hospede = Cliente.find(params[:id])
    end
  
    def update
      @hospede = Cliente.find(params[:id])
  
      if @hospede.update(hospede_params)
        redirect_to admin_hospede_index_path
      else
        render :edit
      end
    end

    def export
      @hospedes = Cliente.all
      @hospede  = @hospede.filter_by_starts_with(params[:nome]) if params[:nome].present?
  
      respond_to do |format|
        format.pdf do
          send_pdf
        end
        format.csv do
          send_csv
        end

      end
    end

    
    private
      def hospede_params
        params.require(:cliente).permit(:nome, :telefone, :cpf, :email)
      end   

      def send_pdf
        colsname = {nome: 'Nome', telefone: 'Telefone', cpf:'CPF', email:'Email'}
        widths = [135, 135, 135, 135]

        relatorio = GeneratePdf.new("Lista de Hospedes", @hospedes, colsname, widths)
        pdf = relatorio.pdf
        send_data(pdf, filename: 'relatorio.pdf', type: 'application/pdf', disposition: :inline)
      end

      def send_csv
        colsname = {nome: 'Nome', telefone: 'Telefone', cpf:'CPF'}

        relatorio = GenerateCsv.new( @hospedes, colsname)
        csv = relatorio.csv
        send_data(csv, filename:'relatorio.csv', type:'text/csv')
    end


end

app/helpers/admin/hospede_helper.rb
module Admin::HospedeHelper
end

app/views/admin/hospede/_form.html.erb
<%= form_with model: hospede, url:url	 do |f|%>
  <div class="mb-3">
    <%= f.label :nome, "Nome", class:"form-label" %>
    <%= f.text_field :nome, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :telefone, "Telefone", class:"form-label" %>
    <%= f.telephone_field :telefone, class:"form-control phone" %>
  </div>

  <div class="mb-3">
    <%= f.label :cpf, "CPF", class:"form-label" %>
    <%= f.text_field :cpf, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :email, "Email", class:"form-label" %>
    <%= f.text_field :email, class:"form-control" %>
  </div>

  <%= f.submit "Salvar", class:"btn btn-primary" %>
<% end %>

app/views/admin/hospede/edit.html.erb
<% content_for :main do %>
  <div class="p-5">
    <%= render partial: "form", locals: {hospede: @hospede, url:admin_hospede_path(@hospede)}  %>
  </div>
<% end %>

app/views/admin/hospede/index.html.erb
<% content_for :main do %>
  <div class="py-3">
    <span>Filtros</span>
    <%= form_with url: admin_hospede_index_path, method: :get do |form| %>
      <div class="px-3 py-2 border d-flex">
        <div class="mb-3 me-2">
          <%= form.label :nome, "Nome:", class: "form-label"%>
          <%= form.text_field :nome, :value=>params[:nome], class: "form-control" %>
        </div>
        <%= form.submit "Search", class: "mt-3 btn btn-primary align-self-center"%>
      </div>
    <% end %>
  </div>

  <div class="py-3 d-flex">
    <%= render "shared/button_create", locals: {nome: "Novo Hospede", url: new_admin_hospede_path} %>
    <div class="ms-3 ">
      <%= render partial: "shared/button_export", locals: {url: -> (f){export_admin_hospede_index_path(format:f)}} %>
    </div>
  </div>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">CPF</th>
        <th scope="col">Telefone</th>
        <th scope="col">Email</th>
        <th scope="col" width="15%"></th>
      </tr>
    </thead>
  <tbody>
    <% @hospede.each_with_index do |item, i| %>
      <tr>
        <th scope="row"><%= "#{i}" %></th>
        <td><%= item.nome%></td>
        <td><%= item.cpf%></td>
        <td><%= item.telefone%></td>
        <td><%= item.email%></td>
        <td>
          <button type="button"  class="btn btn-delete" data-url='<%=admin_hospede_path(item)%>' > 
            <i class="bi bi-trash"></i>
          </button>
          <%= link_to(edit_admin_hospede_path(item), class: 'btn') do %>
            <i class="bi bi-pencil-square"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= paginate @hospede, window: 2 %>
</div>

<%= render "shared/modal_delete" %>

<% end %>

app/views/admin/hospede/new.html.erb
<% content_for :main do %>
  <div class="p-5">
    <%= render partial: "form", locals: {hospede: @hospede, url:admin_hospede_index_path}  %>
  </div>
<% end %>